version: "3.0"
services:
    web:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/hillcroft-cod-club:latest
        container_name: web
        build: 
            context: ./node/.
        volumes:
            - data:/usr/src/app/data
        ports:
            - "8080:8080"
        networks:
            - backend
        depends_on: [python]
        environment: 
            - PORT=${PORT}
    
    python:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/python-scraper:latest
        container_name: python
        build: 
            context: ./python/.
        volumes:
            - data:/home/data
        environment: 
            - COD_API_USER=${COD_API_USER}
            - COD_API_PASSWORD=${COD_API_PASSWORD}
            - MONGO_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - backend
    mongodb:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/mongodb:latest
        container_name: mongodb
        build:
            context: ./mongo/.  
        networks: 
            - backend
        volumes:
            - mongodb_data_container:/data/db 
        environment: 
                - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
                - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    mongoku:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/mongoku
        container_name: mongoku
        build:
            context: ./mongo/mongoku/.
        depends_on: 
            - mongodb
        networks: 
            - backend
        ports:
            - "3100:3100"
        environment: 
            - MONGOKU_DEFAULT_HOST=${MONGOKU_DEFAULT}
            - WAIT_HOSTS=mongodb:27017

volumes:
    data:
    mongodb_data_container:

networks:
    backend:
    
