version: "3.0"
services:
    web:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/hillcroft-cod-club:latest
        container_name: web
        build: 
            context: ./node/.
        volumes:
            - data:/usr/src/app/data
        ports:
            - "${PORT}:${PORT}"
        networks:
            - backend
        depends_on: [python]
        environment: 
            - PORT=${PORT}
            - MONGO_HOST=mongodb:27017
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - COD_PLAYERS=${COD_PLAYERS_HC}
            - SESSION_SECRET=${SESSION_SECRET}
            - BATTLE_CLIENT_ID=${BATTLE_CLIENT_ID}
            - BATTLE_SECRET=${BATTLE_SECRET}
    
    python:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/python-scraper:latest
        container_name: python
        build: 
            context: ./python/.
        volumes:
            - data:/home/data
        environment: 
            - COD_API_USER=${COD_API_USER}
            - COD_API_PASSWORD=${COD_API_PASSWORD}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_HOST=mongodb:27017
            - WAIT_HOSTS=mongodb:27017
            - RUN_SCRAPER=${RUN_SCRAPER}
        networks:
            - backend

    dash:
        container_name: dash
        build: 
            context: ./dash/.
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_HOST=mongodb:27017
            - WAIT_HOSTS=mongodb:27017
            - DASH_HOST=0.0.0.0
            - DASH_PORT=8880
            - COD_PLAYERS=${COD_PLAYERS_HC}
            - TITLE="Hillcroft"
        networks:
            - backend
        ports:
            - "8880:8880"

    dash_thomasridings:
        container_name: dash_thomasridings
        build: 
            context: ./dash/.
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_HOST=mongodb:27017
            - WAIT_HOSTS=mongodb:27017
            - DASH_HOST=0.0.0.0
            - DASH_PORT=8881
            - COD_PLAYERS=${COD_PLAYERS_TR}
            - TITLE="N0085"
        networks:
            - backend
        ports:
            - "8881:8881"

    mongodb:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/mongodb:latest
        container_name: mongodb
        build:
            context: ./mongo/.  
        networks: 
            - backend
        volumes:
            - mongodb_data_container:/data/db 
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"



    mongoku:
        image: 876831597101.dkr.ecr.eu-west-1.amazonaws.com/mongoku
        container_name: mongoku
        build:
            context: ./mongo/mongoku/.
        depends_on: 
            - mongodb
        networks: 
            - backend
        ports:
            - "3100:3100"
        environment: 
            - MONGOKU_DEFAULT_HOST=${MONGOKU_DEFAULT}
            - WAIT_HOSTS=mongodb:27017

volumes:
    data:
    mongodb_data_container:

networks:
    backend:
    
